### ISSUE TITLE
error for export_pseudobulk

### ISSUE THREAD

**Issue by aaaaaaaaaayong** [aertslab/scenicplus#314]
#Describe the bug
  When  I apply my data to export_pseudobulk function  of SCENIC+ pipeline,I meet error.
  I don't know where this file（ADM.fragments.tsv.gz ） came from ，I have never imported this file.

#Code

```
> work_dir = '/public/home/chenxy/data/Synapse/scenicplus/00_data.import'
> fragments_dict = {'pancan': os.path.join(work_dir, 'scATAC/fragments/gz/pancan_fragments.tsv.gz')}
> bw_paths, bed_paths = export_pseudobulk(input_data = cell_data,
>                  variable = 'cell_type',                                                                    
>                  sample_id_col = 'sample_id',
>                  chromsizes = chromsizes,
>                  bed_path = os.path.join(work_dir, 'scATAC/consensus_peak_calling/pseudobulk_bed_files/'),  
>                  bigwig_path = os.path.join(work_dir, 'scATAC/consensus_peak_calling/pseudobulk_bw_files/'),
>                  path_to_fragments = fragments_dict,                                                     
>                  n_cpu = 8,                                                                                
>                  normalize_bigwig = True,
>                  temp_dir = os.path.join(tmp_dir, 'ray_spill'),
>                  split_pattern = '-')
```

#Error output
     raise ValueError(f"Fragment file {path_to_fragment_file} does not exist.")
     ValueError: Fragment file /public/home/chenxy/data/Synapse/scenicplus/00_data.import/ray_spill/pancan/ADM.fragments.tsv.gz does not exist.

#Additional context
   This fragments file is created by merging multiple fragments files. I refer to this process
  

```
> gzip -dc atac_pbmc_500_nextgem_fragments.tsv.gz | awk 'BEGIN {FS=OFS="\t"} {print $1,$2,$3,"500_"$4,$5}' - > pbmc500_fragments.tsv
> gzip -dc atac_pbmc_1k_nextgem_fragments.tsv.gz | awk 'BEGIN {FS=OFS="\t"} {print $1,$2,$3,"1k_"$4,$5}' - > pbmc1k_fragments.tsv
> gzip -dc atac_pbmc_5k_nextgem_fragments.tsv.gz | awk 'BEGIN {FS=OFS="\t"} {print $1,$2,$3,"5k_"$4,$5}' - > pbmc5k_fragments.tsv
> gzip -dc atac_pbmc_10k_nextgem_fragments.tsv.gz | awk 'BEGIN {FS=OFS="\t"} {print $1,$2,$3,"10k_"$4,$5}' - > pbmc10k_fragments.tsv
> sort -m -k 1,1V -k2,2n pbmc500_fragments.tsv pbmc1k_fragments.tsv pbmc5k_fragments.tsv pbmc10k_fragments.tsv > fragments.tsv
> bgzip -@ 4 fragments.tsv
> tabix -p bed fragments.tsv.gz
```

#Version (please complete the following information):**
 - Python: 3.8.18
 - SCENIC+

**Comment by SeppeDeWinter** [comment]
Hi @aaaaaaaaaayong 

The function `export_pseudobulk` will generate a fragments file for each variable (for you `cell_type`), so that's where this file is supposed to come from. This error is generated because this file is not generated in your case (while it should be).

This can be caused when the function is not able to match cell barcodes between your `cell_data` dataframe and the fragments file.

The reason for this is probably because you appended sample ids to the barcodes in your fragments file ("500_" for example). It's not necessary to merge your fragment files before running pycistopic/SCENIC+. You can just specify multiple files in your `fragments_dict` variable. Is there any particular reason why you are merging the files beforehand?

Also could you show the head of `cell_data` and one of your fragment files?

All the best,

Seppe

**Comment by aaaaaaaaaayong** [comment]
@SeppeDeWinter  

Thank you very much for your reply，but I still haven't solved the problem, I tried without merging and just inputting one fragments file， It still reports the error. 

Also I checked the cell barcodes between my cell_data dataframe and the fragments file , and didn't find any difference between them. I added "_n" (for example "_1") at the end of the barcodes to distinguish different sample sources. 

This is one of my fragment files:
```
chr1    10073   10351   CGCAATGTCACCTGTC-1_16   1
chr1    10079   10303   GCTTAACAGCGTGCGT-1_16   1
chr1    10083   10334   TGTAACTCAATCCCTT-1_16   1
chr1    10084   10334   AAAGCTTGTTTGGGCG-1_16   1
chr1    10085   10279   AATTGCTCATTGTTGG-1_16   1
chr1    10085   10303   TACTCAAAGGCCTTAG-1_16   1
chr1    10085   10308   CGTGAGGAGACTTATG-1_16   1
chr1    10085   10333   TCTTGACGTCAACAAT-1_16   1
chr1    10091   10279   TAGCCTCTCCCTGGAA-1_16   1
chr1    10091   10285   ATCGAGGCAGGGAGCT-1_16   1
chr1    10091   10315   TAGTAGGAGTGATTCA-1_16   1
chr1    10097   10277   CGCAATGTCCCAGTAG-1_16   1
chr1    10102   10279   GCTCACAAGTAGCTTA-1_16   1

```

And head of cell_data:
```
>>> cell_data
                      Cancer  Case_ID Chemistry      Piece_ID  ...  seurat_clusters    total unmapped sample_id
CellID                                                         ...                                             
AAACAGCCAAGGACCA-1_1    CESC    CE340  Multiome  CE340E1-S1N1  ...              4.0   6949.0    105.0    pancan
AAACAGCCATTAAAGG-1_1    CESC    CE340  Multiome  CE340E1-S1N1  ...              1.0   4585.0     74.0    pancan
AAACATGCACATGCTA-1_1    CESC    CE340  Multiome  CE340E1-S1N1  ...              1.0  12807.0    152.0    pancan
AAACATGCAGCTTAGC-1_1    CESC    CE340  Multiome  CE340E1-S1N1  ...             25.0  55895.0    609.0    pancan
AAACATGCATCCATCT-1_1    CESC    CE340  Multiome  CE340E1-S1N1  ...              1.0   7527.0     95.0    pancan
...                      ...      ...       ...           ...  ...              ...      ...      ...       ...
TTTGTGAAGTAGGATG-1_24     OV  VF050V1  Multiome  VF050V1-S2N1  ...              4.0   8639.0    127.0    pancan
TTTGTGGCAAACCCTA-1_24     OV  VF050V1  Multiome  VF050V1-S2N1  ...             17.0  11327.0    178.0    pancan
TTTGTGGCATAATCCG-1_24     OV  VF050V1  Multiome  VF050V1-S2N1  ...             17.0   9034.0    138.0    pancan
TTTGTGTTCTAATCCT-1_24     OV  VF050V1  Multiome  VF050V1-S2N1  ...             17.0   4181.0     73.0    pancan
TTTGTTGGTTATAGCG-1_24     OV  VF050V1  Multiome  VF050V1-S2N1  ...              4.0  10381.0    168.0    pancan

[131155 rows x 64 columns]
```

Thanks again for your help and Wish you all the best.

ayong

**Comment by SeppeDeWinter** [comment]
Hi Ayong

Can you try without adding the "_n", cistopic will automatically append sample ids to your cell barcodes.

All the best,

Seppe

**Comment by aaaaaaaaaayong** [comment]
HI HI Seppe

Your guidance helped me find an idea. I think this problem has been solved, although the program was killed due to insufficient memory

There are cores to solving the problem:
1）Index names must contain the BARCODE (e.g. ATGTCGTC-1), additional tags are possible separating with -  (e.g. ATGCTGTGCG-1-Sample_1)
2）I added a column called 'barcode'，which will be used instead of the index names
3)  The keys of the dictionary need to match with the sample_id tag added to the index names of the input data frame.

Such as:
```
>>> cell_data['barcode']
CellID
AAACAGCCAAGGACCA-1_1      AAACAGCCAAGGACCA-1-Sample_1
AAACAGCCATTAAAGG-1_1      AAACAGCCATTAAAGG-1-Sample_1
AAACATGCACATGCTA-1_1      AAACATGCACATGCTA-1-Sample_1
AAACATGCAGCTTAGC-1_1      AAACATGCAGCTTAGC-1-Sample_1
AAACATGCATCCATCT-1_1      AAACATGCATCCATCT-1-Sample_1
                                     ...             
TTTGTGAAGTAGGATG-1_24    TTTGTGAAGTAGGATG-1-Sample_24
TTTGTGGCAAACCCTA-1_24    TTTGTGGCAAACCCTA-1-Sample_24
TTTGTGGCATAATCCG-1_24    TTTGTGGCATAATCCG-1-Sample_24
TTTGTGTTCTAATCCT-1_24    TTTGTGTTCTAATCCT-1-Sample_24
TTTGTTGGTTATAGCG-1_24    TTTGTTGGTTATAGCG-1-Sample_24
```

```
>>> cell_data['Sample_id']
CellID
AAACAGCCAAGGACCA-1_1      Sample_1
AAACAGCCATTAAAGG-1_1      Sample_1
AAACATGCACATGCTA-1_1      Sample_1
AAACATGCAGCTTAGC-1_1      Sample_1
AAACATGCATCCATCT-1_1      Sample_1
                           ...    
TTTGTGAAGTAGGATG-1_24    Sample_24
TTTGTGGCAAACCCTA-1_24    Sample_24
TTTGTGGCATAATCCG-1_24    Sample_24
TTTGTGTTCTAATCCT-1_24    Sample_24
TTTGTTGGTTATAGCG-1_24    Sample_24
```

```
less CE340E1-S1_fragments.tsv.gz
chr1    10072   10278   GTAGGATCACCTAATG-1-Sample_1     1
chr1    10079   10302   CGCCACACAAGCTAAA-1-Sample_1     1
chr1    10079   10327   ATTAGCTCACCATATG-1-Sample_1     1
chr1    10084   10436   GATGCTTAGGGACTAA-1-Sample_1     1
chr1    10090   10333   CCGTTTGGTGGGAACA-1-Sample_1     1
chr1    10131   10279   CCAACCAAGACAAAGT-1-Sample_1     1
chr1    10132   10279   CCAACCAAGACAAAGT-1-Sample_1     1
chr1    10151   10185   GGTACCGGTTGGTTAG-1-Sample_1     2
chr1    10151   10215   CTTGCATGTTTAACCC-1-Sample_1     2
chr1    10151   10216   GAGGGAGCAAGGCCAA-1-Sample_1     1
```
```
fragments_dict = {
                  'Sample_1': os.path.join(work_dir, 'scATAC/test/CE340E1-S1_fragments.tsv.gz'),
                  'Sample_2': os.path.join(work_dir, 'scATAC/test/CM1563C1-T1_fragments.tsv.gz'),
                                                                        ...    
                  'Sample_23': os.path.join(work_dir, 'scATAC/test/VF034V1-T1_fragments.tsv.gz'),
                  'Sample_24': os.path.join(work_dir, 'scATAC/test/VF050V1-S2_fragments.tsv.gz')
                  }
```

Thanks for your help and Wish you all the best.

Ayong

**Comment by SeppeDeWinter** [comment]
Hi @aaaaaaaaaayong 

Great to hear that your issue is solved.

I wish you all the best as well and good luck with your analyses.

I'm closing this issue now feel free to open new ones.

Seppe

**Comment by yojetsharma** [comment]
> HI HI Seppe
> 
> Your guidance helped me find an idea. This problem has been solved.
> 
> And because the data sources are different,there are a lot of duplications in their barcodes .So I added my own tags.
> 
> There are cores to solving the problem: 1）Index names must contain the BARCODE (e.g. ATGTCGTC-1), additional tags are possible separating with - (e.g. ATGCTGTGCG-1-Sample_1) 2）I added a column called 'barcode'，which will be used instead of the index names 3) The keys of the dictionary need to match with the sample_id tag added to the index names of the input data frame(now that is 'barcode').
> 
> Such as:
> 
> ```
> >>> cell_data['barcode']
> CellID
> AAACAGCCAAGGACCA-1_1      AAACAGCCAAGGACCA-1-Sample_1
> AAACAGCCATTAAAGG-1_1      AAACAGCCATTAAAGG-1-Sample_1
> AAACATGCACATGCTA-1_1      AAACATGCACATGCTA-1-Sample_1
> AAACATGCAGCTTAGC-1_1      AAACATGCAGCTTAGC-1-Sample_1
> AAACATGCATCCATCT-1_1      AAACATGCATCCATCT-1-Sample_1
>                                      ...             
> TTTGTGAAGTAGGATG-1_24    TTTGTGAAGTAGGATG-1-Sample_24
> TTTGTGGCAAACCCTA-1_24    TTTGTGGCAAACCCTA-1-Sample_24
> TTTGTGGCATAATCCG-1_24    TTTGTGGCATAATCCG-1-Sample_24
> TTTGTGTTCTAATCCT-1_24    TTTGTGTTCTAATCCT-1-Sample_24
> TTTGTTGGTTATAGCG-1_24    TTTGTTGGTTATAGCG-1-Sample_24
> ```
> 
> ```
> >>> cell_data['Sample_id']
> CellID
> AAACAGCCAAGGACCA-1_1      Sample_1
> AAACAGCCATTAAAGG-1_1      Sample_1
> AAACATGCACATGCTA-1_1      Sample_1
> AAACATGCAGCTTAGC-1_1      Sample_1
> AAACATGCATCCATCT-1_1      Sample_1
>                            ...    
> TTTGTGAAGTAGGATG-1_24    Sample_24
> TTTGTGGCAAACCCTA-1_24    Sample_24
> TTTGTGGCATAATCCG-1_24    Sample_24
> TTTGTGTTCTAATCCT-1_24    Sample_24
> TTTGTTGGTTATAGCG-1_24    Sample_24
> ```
> 
> ```
> less CE340E1-S1_fragments.tsv.gz
> chr1    10072   10278   GTAGGATCACCTAATG-1-Sample_1     1
> chr1    10079   10302   CGCCACACAAGCTAAA-1-Sample_1     1
> chr1    10079   10327   ATTAGCTCACCATATG-1-Sample_1     1
> chr1    10084   10436   GATGCTTAGGGACTAA-1-Sample_1     1
> chr1    10090   10333   CCGTTTGGTGGGAACA-1-Sample_1     1
> chr1    10131   10279   CCAACCAAGACAAAGT-1-Sample_1     1
> chr1    10132   10279   CCAACCAAGACAAAGT-1-Sample_1     1
> chr1    10151   10185   GGTACCGGTTGGTTAG-1-Sample_1     2
> chr1    10151   10215   CTTGCATGTTTAACCC-1-Sample_1     2
> chr1    10151   10216   GAGGGAGCAAGGCCAA-1-Sample_1     1
> ```
> 
> ```
> fragments_dict = {
>                   'Sample_1': os.path.join(work_dir, 'scATAC/test/CE340E1-S1_fragments.tsv.gz'),
>                   'Sample_2': os.path.join(work_dir, 'scATAC/test/CM1563C1-T1_fragments.tsv.gz'),
>                                                                         ...    
>                   'Sample_23': os.path.join(work_dir, 'scATAC/test/VF034V1-T1_fragments.tsv.gz'),
>                   'Sample_24': os.path.join(work_dir, 'scATAC/test/VF050V1-S2_fragments.tsv.gz')
>                   }
> ```
> 
> Thanks for your help and Wish you all the best.
> 
> Ayong

How can we update the fragments barcodes with the sample prefixes? 

My fragments barcode look like this:
DataFrame structure:
```
      0      1           2                   3  
0  chr1  10066  10191  CGTAACCTCTAACCCA-1 
1  chr1  10073  10612  TCAATCTAGGATTATG-1 
2  chr1  10077  10285  GTATTGCGTTACTTCT-1 
3  chr1  10079  10487  GTTGTGGAGGCACTAG-1 
4  chr1  10079  10512  TGAATCCGTAGCTTAC-1 
Columns in DataFrame: Int64Index([0, 1, 2, 3, 4], dtype='int64')
Extracted barcodes preview: ['CGTAACCTCTAACCCA-1' 'TCAATCTAGGATTATG-1' 'GTATTGCGTTACTTCT-1'
 'GTTGTGGAGGCACTAG-1' 'TGAATCCGTAGCTTAC-1']
```
 
 While the ones in the cell_data extracted from the snRNA seq of the same samples look like this:
```
  	                                       sample 	 leiden 	                   barcode
AAACAGCCAAATATCC-1 	d149 	Radial glia type 1 	AAACAGCCAAATATCC-1
AAACAGCCAATGCGCT-1 	d149 	Radial glia type 1 	AAACAGCCAATGCGCT-1
AAACAGCCAATTGCGC-1 	d149 	Radial glia type 1 	AAACAGCCAATTGCGC-1
AAACAGCCACAATGTT-1 	d149 	Radial glia type 1 	AAACAGCCACAATGTT-1
AAACAGCCAGTATGTT-1 	d149 	Radial glia type 1 	AAACAGCCAGTATGTT-1
```
But I am still getting the error:
`ValueError: Fragment file /tmp/d149/AAACAGCCAAACCTTG-1.fragments.tsv.gz does not exist.`

**Comment by Melody-cell** [comment]
> Hi @aaaaaaaaaayong
> 
> Great to hear that your issue is solved.
> 
> I wish you all the best as well and good luck with your analyses.
> 
> I'm closing this issue now feel free to open new ones.
> 
> Seppe

Hi, @SeppeDeWinter , i've encountered the same problem,
but i can't find any mistakes in my data.
1.This is my cell_data:
![image](https://github.com/user-attachments/assets/914c988b-c1ff-40ae-a7fa-dfdb025819c4)
2.This is my fragments:
![image](https://github.com/user-attachments/assets/bf26ec1c-8c40-49e3-beeb-f51e6c1675e9)
It looks very well.
But it appears this:
ValueError: Fragment file /b01_10hpf_cisTopic/tmp/5/NMPs.fragments.tsv.gz does not exist.
Could you help me?

**Comment by SeppeDeWinter** [comment]
Hi @Melody-cell 

Are other pseudobulk fragments files also not created or is it just for this one cell type?

Best,

S

**Comment by icenzano** [comment]
Hi I'm having the following error when trying to run export_pseudobulk.


---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[155], line 1
----> 1 bw_paths, bed_paths = export_pseudobulk(input_data = cell_data,
      2                  variable = 'cell_type', # cell type annotation
      3                  sample_id_col = 'sample_id',
      4                  chromsizes = chromsizes,
      5                  bed_path = outDir + 'consensus_peak_calling[/pseudobulk_bed_files/](http://127.0.0.1:47579/pseudobulk_bed_files/)',
      6                  bigwig_path = outDir + 'consensus_peak_calling[/pseudobulk_bw_files/](http://127.0.0.1:47579/pseudobulk_bw_files/)',
      7                  path_to_fragments = fragments_dict,
      8                  n_cpu = 10,
      9                  normalize_bigwig = True,
     10                  temp_dir = tmpDir,
     11                  split_pattern = None)

File [/ibex/user/armendic/conda-environments/scenicplus/lib/python3.11/site-packages/pycisTopic/pseudobulk_peak_calling.py:162](http://127.0.0.1:47579/ibex/user/armendic/conda-environments/scenicplus/lib/python3.11/site-packages/pycisTopic/pseudobulk_peak_calling.py#line=161), in export_pseudobulk(input_data, variable, chromsizes, bed_path, bigwig_path, path_to_fragments, sample_id_col, n_cpu, normalize_bigwig, split_pattern, temp_dir)
    159 # For each sample, get fragments for each cell type
    161 log.info("Splitting fragments by cell type.")
--> 162 split_fragment_files_by_cell_type(
    163     sample_to_fragment_file = path_to_fragments,
    164     path_to_temp_folder = temp_dir,
    165     path_to_output_folder = bed_path,
    166     sample_to_cell_type_to_cell_barcodes = sample_to_cell_type_to_barcodes,
    167     chromsizes = chromsizes_dict,
    168     n_cpu = n_cpu,
    169     verbose = False,
    170     clear_temp_folder = True
    171 )
    173 bed_paths = {}
    174 for cell_type in cell_data[variable].unique():

File [/ibex/user/armendic/conda-environments/scenicplus/lib/python3.11/site-packages/scatac_fragment_tools/library/split/split_fragments_by_cell_type.py:92](http://127.0.0.1:47579/ibex/user/armendic/conda-environments/scenicplus/lib/python3.11/site-packages/scatac_fragment_tools/library/split/split_fragments_by_cell_type.py#line=91), in split_fragment_files_by_cell_type(sample_to_fragment_file, path_to_temp_folder, path_to_output_folder, sample_to_cell_type_to_cell_barcodes, chromsizes, n_cpu, verbose, clear_temp_folder)
     90 path_to_fragment_file = os.path.join(path_to_temp_folder, sample, f"{cell_type_sanitized}.fragments.tsv.gz")
     91 if not os.path.exists(path_to_fragment_file):
---> 92     raise ValueError(f"Fragment file {path_to_fragment_file} does not exist.")
     93 if cell_type_sanitized not in cell_type_to_fragment_files:
     94     cell_type_to_fragment_files[cell_type_sanitized] = []

ValueError: Fragment file NEWtmp[/ACBM637/Cluster0.fragments.tsv.gz](http://127.0.0.1:47579/ACBM637/Cluster0.fragments.tsv.gz) does not exist.

**Comment by Melody-cell** [comment]
> Hi @Melody-cell
> 
> Are other pseudobulk fragments files also not created or is it just for this one cell type?
> 
> Best,
> 
> S

Hi, thank you for your help, i have solved it now.
Cause my chromosome in the first column didn't add "chr".

**Comment by Mr-Kaw** [comment]
Hi @SeppeDeWinter , I'm having the same issue with export_pseudobulk,
my cell_data looks like this:

<img width="434" height="354" alt="Image" src="https://github.com/user-attachments/assets/d5606dfe-26e3-44d5-b812-d19c6dfdfd43" />

and my fragment file looks like this:

<img width="445" height="578" alt="Image" src="https://github.com/user-attachments/assets/7452f080-1098-4e8a-94ab-f506c11bb67a" />

searched through issues a lot but still couldn't figure out what the problem was. Any clue? Thanks.

**Comment by Mr-Kaw** [comment]
> Hi [@SeppeDeWinter](https://github.com/SeppeDeWinter) , I'm having the same issue with export_pseudobulk, my cell_data looks like this:
> 
> <img alt="Image" width="434" height="354" src="https://private-user-images.githubusercontent.com/164977731/527721652-d5606dfe-26e3-44d5-b812-d19c6dfdfd43.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjYwNTcxMTIsIm5iZiI6MTc2NjA1NjgxMiwicGF0aCI6Ii8xNjQ5Nzc3MzEvNTI3NzIxNjUyLWQ1NjA2ZGZlLTI2ZTMtNDRkNS1iODEyLWQxOWM2ZGZkZmQ0My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTIxOFQxMTIwMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMDgwZjlkNjZjOTliMWZlYTZiYjU5MmRmYzFiZTMxMjBkMzEwMTBjOGJiNGZmMWUwZWRmOTE0Mjg5ZmI3MTQ3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Y10Ixztotm8QLJsI0v7lQ3ewVCPHw0WynaKaAnj8LaA">
> and my fragment file looks like this:
> 
> <img alt="Image" width="445" height="578" src="https://private-user-images.githubusercontent.com/164977731/527721921-7452f080-1098-4e8a-94ab-f506c11bb67a.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjYwNTcxMTIsIm5iZiI6MTc2NjA1NjgxMiwicGF0aCI6Ii8xNjQ5Nzc3MzEvNTI3NzIxOTIxLTc0NTJmMDgwLTEwOTgtNGU4YS05NGFiLWY1MDZjMTFiYjY3YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTIxOFQxMTIwMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MzY1ZDY3ZGY4MDExYmZmODA3NjIzODJlNzlmMmE5OWQ4ZmI5ZjIyYTI2MDA0Njk1OWFmYzhmOWUwZjBlMjkxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.yfj-Z_unVndEYJrPl3uxChMyzL-5B4uaBJPM6ya9aL0">
> searched through issues a lot but still couldn't figure out what the problem was. Any clue? Thanks.

alright, I've found the problem, the original tsv.gz contained comments starting with '#', so I tried unzipping the file and deleting the comments, then I gzipped them again and now the error changed into something else so that's progress!

**Comment by Mr-Kaw** [comment]
> > Hi [@SeppeDeWinter](https://github.com/SeppeDeWinter) , I'm having the same issue with export_pseudobulk, my cell_data looks like this:
> > <img alt="Image" width="434" height="354" src="https://private-user-images.githubusercontent.com/164977731/527721652-d5606dfe-26e3-44d5-b812-d19c6dfdfd43.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjYwNTcxMTIsIm5iZiI6MTc2NjA1NjgxMiwicGF0aCI6Ii8xNjQ5Nzc3MzEvNTI3NzIxNjUyLWQ1NjA2ZGZlLTI2ZTMtNDRkNS1iODEyLWQxOWM2ZGZkZmQ0My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTIxOFQxMTIwMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMDgwZjlkNjZjOTliMWZlYTZiYjU5MmRmYzFiZTMxMjBkMzEwMTBjOGJiNGZmMWUwZWRmOTE0Mjg5ZmI3MTQ3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Y10Ixztotm8QLJsI0v7lQ3ewVCPHw0WynaKaAnj8LaA">
> > and my fragment file looks like this:
> > <img alt="Image" width="445" height="578" src="https://private-user-images.githubusercontent.com/164977731/527721921-7452f080-1098-4e8a-94ab-f506c11bb67a.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjYwNTcxMTIsIm5iZiI6MTc2NjA1NjgxMiwicGF0aCI6Ii8xNjQ5Nzc3MzEvNTI3NzIxOTIxLTc0NTJmMDgwLTEwOTgtNGU4YS05NGFiLWY1MDZjMTFiYjY3YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTIxOFQxMTIwMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MzY1ZDY3ZGY4MDExYmZmODA3NjIzODJlNzlmMmE5OWQ4ZmI5ZjIyYTI2MDA0Njk1OWFmYzhmOWUwZjBlMjkxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.yfj-Z_unVndEYJrPl3uxChMyzL-5B4uaBJPM6ya9aL0">
> > searched through issues a lot but still couldn't figure out what the problem was. Any clue? Thanks.
> 
> alright, I've found the problem, the original tsv.gz contained comments starting with '#', so I tried unzipping the file and deleting the comments, then I gzipped them again and now the error changed into something else so that's progress!

so AI suggests the new error occurred because I used gzip instead of bgzip, so I ran a bgzip but it didn't fix it, and it suggested I should run another tabix on the tsv.gz so I did that too, now it seems to be working without errors. Hoorray!
